"""mergerlab: calibrated merger simulation and antitrust screening."""

from .case import Analysis, Case, CaseError, analyze, load_case, parse_case
from .demand import (
    CES,
    PCAIDS,
    Calibration,
    Demand,
    Linear,
    Logit,
    NestedLogit,
    calibrate_ces,
    calibrate_linear,
    calibrate_logit,
    calibrate_logit_alm,
    calibrate_nested_logit,
    calibrate_pcaids,
)
from .errors import CalibrationError, EquilibriumNotFound
from .koh import (
    HarmComparison,
    KohDecomposition,
    first_order_harm_error,
    harm_comparison,
    koh_decomposition,
    koh_rho1,
)
from .market import Market
from .metrics import (
    CMCR,
    cmcr_from_demand,
    cmcr_from_diversion,
    cmcr_two_product,
    compensating_variation,
    cost_pressure,
    critical_efficiency,
    critical_loss,
    diversion_from_demand,
    first_order_price_effects,
    guppi,
    guppi_matrix,
    hypothetical_monopolist_test,
    merger_pass_through,
    pricing_pressure,
    producer_surplus,
    synergy_amounts,
    upp,
)
from .remedies import DivestitureOption, DivestitureReport, evaluate_divestitures
from .screens import (
    Concentration,
    concentration,
    delta_hhi_pair,
    hhi,
    screen,
    screen_eu2004,
    screen_us2010,
    screen_us2023,
)
from .simulate import ModelSpec, SimulationResult, simulate_merger, simulate_one
from .supply import Equilibrium, recover_costs, solve_bertrand
from .uncertainty import MonteCarloResult, Priors, run_monte_carlo
from .units import Diversion, DiversionBasis, MarginKind, Margins, Ownership, ShareBasis, Shares

__version__ = "0.1.0"

__all__ = [
    "CES",
    "CMCR",
    "PCAIDS",
    "Analysis",
    "Calibration",
    "CalibrationError",
    "Case",
    "CaseError",
    "Concentration",
    "Demand",
    "Diversion",
    "DiversionBasis",
    "DivestitureOption",
    "DivestitureReport",
    "Equilibrium",
    "EquilibriumNotFound",
    "HarmComparison",
    "KohDecomposition",
    "Linear",
    "Logit",
    "MarginKind",
    "Margins",
    "Market",
    "ModelSpec",
    "MonteCarloResult",
    "NestedLogit",
    "Ownership",
    "Priors",
    "ShareBasis",
    "Shares",
    "SimulationResult",
    "__version__",
    "analyze",
    "calibrate_ces",
    "calibrate_linear",
    "calibrate_logit",
    "calibrate_logit_alm",
    "calibrate_nested_logit",
    "calibrate_pcaids",
    "cmcr_from_demand",
    "cmcr_from_diversion",
    "cmcr_two_product",
    "compensating_variation",
    "concentration",
    "cost_pressure",
    "critical_efficiency",
    "critical_loss",
    "delta_hhi_pair",
    "diversion_from_demand",
    "evaluate_divestitures",
    "first_order_harm_error",
    "first_order_price_effects",
    "guppi",
    "guppi_matrix",
    "harm_comparison",
    "hhi",
    "hypothetical_monopolist_test",
    "koh_decomposition",
    "koh_rho1",
    "load_case",
    "merger_pass_through",
    "parse_case",
    "pricing_pressure",
    "producer_surplus",
    "recover_costs",
    "run_monte_carlo",
    "screen",
    "screen_eu2004",
    "screen_us2010",
    "screen_us2023",
    "simulate_merger",
    "simulate_one",
    "solve_bertrand",
    "synergy_amounts",
    "upp",
]
